export const products = [
    {
        "id": 1,
        "name": "Apple",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Red_Apple.jpg/265px-Red_Apple.jpg",
        "price": 35
    },
    {
        "id": 2,
        "name": "Banana",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Bananas_white_background_DS.jpg/320px-Bananas_white_background_DS.jpg",
        "price": 12
    },
    {
        "id": 3,
        "name": "Grapes",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bb/Table_grapes_on_white.jpg/320px-Table_grapes_on_white.jpg",
        "weight": 0.1,
        "price": 45
    },
    {
        "id": 4,
        "name": "Pineapple",
        "image": "https://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Pineapple_and_cross_section.jpg/286px-Pineapple_and_cross_section.jpg",
        "price": 200
    }
];

export const countries = [
    { id: "1", text: "Afghanistan" },
    { id: "2", text: "Albania" },
    { id: "3", text: "Algeria" },
    { id: "4", text: "Andorra" },
    { id: "5", text: "Angola" },
    { id: "6", text: "Antigua and Barbuda" },
    { id: "7", text: "Argentina" },
    { id: "8", text: "Armenia" },
    { id: "9", text: "Australia" },
    { id: "10", text: "Austria" },
    { id: "11", text: "Azerbaijan" },
    { id: "12", text: "The Bahamas" },
    { id: "13", text: "Bahrain" },
    { id: "14", text: "Bangladesh" },
    { id: "15", text: "Barbados" },
    { id: "16", text: "Belarus" },
    { id: "17", text: "Belgium" },
    { id: "18", text: "Belize" },
    { id: "19", text: "Benin" },
    { id: "20", text: "Bhutan" },
    { id: "21", text: "Bolivia" },
    { id: "22", text: "Bosnia and Herzegovina" },
    { id: "23", text: "Botswana" },
    { id: "24", text: "Brazil" },
    { id: "25", text: "Brunei" },
    { id: "26", text: "Bulgaria" },
    { id: "27", text: "Burkina Faso" },
    { id: "28", text: "Burundi" },
    { id: "29", text: "Cabo Verde" },
    { id: "30", text: "Cambodia" },
    { id: "31", text: "Cameroon" },
    { id: "32", text: "Canada" },
    { id: "33", text: "Central African Republic" },
    { id: "34", text: "Chad" },
    { id: "35", text: "Chile" },
    { id: "36", text: "China" },
    { id: "37", text: "Colombia" },
    { id: "38", text: "Comoros" },
    { id: "39", text: "Congo, Democratic Republic of the" },
    { id: "40", text: "Congo, Republic of the" },
    { id: "41", text: "Costa Rica" },
    { id: "42", text: "Côte d’Ivoire" },
    { id: "43", text: "Croatia" },
    { id: "44", text: "Cuba" },
    { id: "45", text: "Cyprus" },
    { id: "46", text: "Czech Republic" },
    { id: "47", text: "Denmark" },
    { id: "48", text: "Djibouti" },
    { id: "49", text: "Dominica" },
    { id: "50", text: "Dominican Republic" },
    { id: "51", text: "East Timor (Timor-Leste)" },
    { id: "52", text: "Ecuador" },
    { id: "53", text: "Egypt" },
    { id: "54", text: "El Salvador" },
    { id: "55", text: "Equatorial Guinea" },
    { id: "56", text: "Eritrea" },
    { id: "57", text: "Estonia" },
    { id: "58", text: "Eswatini" },
    { id: "59", text: "Ethiopia" },
    { id: "60", text: "Fiji" },
    { id: "61", text: "Finland" },
    { id: "62", text: "France" },
    { id: "63", text: "Gabon" },
    { id: "64", text: "The Gambia" },
    { id: "65", text: "Georgia" },
    { id: "66", text: "Germany" },
    { id: "67", text: "Ghana" },
    { id: "68", text: "Greece" },
    { id: "69", text: "Grenada" },
    { id: "70", text: "Guatemala" },
    { id: "71", text: "Guinea" },
    { id: "72", text: "Guinea-Bissau" },
    { id: "73", text: "Guyana" },
    { id: "74", text: "Haiti" },
    { id: "75", text: "Honduras" },
    { id: "76", text: "Hungary" },
    { id: "77", text: "Iceland" },
    { id: "78", text: "India" },
    { id: "79", text: "Indonesia" },
    { id: "80", text: "Iran" },
    { id: "81", text: "Iraq" },
    { id: "82", text: "Ireland" },
    { id: "83", text: "Israel" },
    { id: "84", text: "Italy" },
    { id: "85", text: "Jamaica" },
    { id: "86", text: "Japan" },
    { id: "87", text: "Jordan" },
    { id: "88", text: "Kazakhstan" },
    { id: "89", text: "Kenya" },
    { id: "90", text: "Kiribati" },
    { id: "91", text: "Korea, North" },
    { id: "92", text: "Korea, South" },
    { id: "93", text: "Kosovo" },
    { id: "94", text: "Kuwait" },
    { id: "95", text: "Kyrgyzstan" },
    { id: "96", text: "Laos" },
    { id: "97", text: "Latvia" },
    { id: "98", text: "Lebanon" },
    { id: "99", text: "Lesotho" },
    { id: "100", text: "Liberia" },
    { id: "101", text: "Libya" },
    { id: "102", text: "Liechtenstein" },
    { id: "103", text: "Lithuania" },
    { id: "104", text: "Luxembourg" },
    { id: "105", text: "Madagascar" },
    { id: "106", text: "Malawi" },
    { id: "107", text: "Malaysia" },
    { id: "108", text: "Maldives" },
    { id: "109", text: "Mali" },
    { id: "110", text: "Malta" },
    { id: "111", text: "Marshall Islands" },
    { id: "112", text: "Mauritania" },
    { id: "113", text: "Mauritius" },
    { id: "114", text: "Mexico" },
    { id: "115", text: "Micronesia, Federated States of" },
    { id: "116", text: "Moldova" },
    { id: "117", text: "Monaco" },
    { id: "118", text: "Mongolia" },
    { id: "119", text: "Montenegro" },
    { id: "120", text: "Morocco" },
    { id: "121", text: "Mozambique" },
    { id: "122", text: "Myanmar (Burma)" },
    { id: "123", text: "Namibia" },
    { id: "124", text: "Nauru" },
    { id: "125", text: "Nepal" },
    { id: "126", text: "Netherlands" },
    { id: "127", text: "New Zealand" },
    { id: "128", text: "Nicaragua" },
    { id: "129", text: "Niger" },
    { id: "130", text: "Nigeria" },
    { id: "131", text: "North Macedonia" },
    { id: "132", text: "Norway" },
    { id: "133", text: "Oman" },
    { id: "134", text: "Pakistan" },
    { id: "135", text: "Palau" },
    { id: "136", text: "Panama" },
    { id: "137", text: "Papua New Guinea" },
    { id: "138", text: "Paraguay" },
    { id: "139", text: "Peru" },
    { id: "140", text: "Philippines" },
    { id: "141", text: "Poland" },
    { id: "142", text: "Portugal" },
    { id: "143", text: "Qatar" },
    { id: "144", text: "Romania" },
    { id: "145", text: "Russia" },
    { id: "146", text: "Rwanda" },
    { id: "147", text: "Saint Kitts and Nevis" },
    { id: "148", text: "Saint Lucia" },
    { id: "149", text: "Saint Vincent and the Grenadines" },
    { id: "150", text: "Samoa" },
    { id: "151", text: "San Marino" },
    { id: "152", text: "Sao Tome and Principe" },
    { id: "153", text: "Saudi Arabia" },
    { id: "154", text: "Senegal" },
    { id: "155", text: "Serbia" },
    { id: "156", text: "Seychelles" },
    { id: "157", text: "Sierra Leone" },
    { id: "158", text: "Singapore" },
    { id: "159", text: "Slovakia" },
    { id: "160", text: "Slovenia" },
    { id: "161", text: "Solomon Islands" },
    { id: "162", text: "Somalia" },
    { id: "163", text: "South Africa" },
    { id: "164", text: "Spain" },
    { id: "165", text: "Sri Lanka" },
    { id: "166", text: "Sudan" },
    { id: "167", text: "Sudan, South" },
    { id: "168", text: "Suriname" },
    { id: "169", text: "Sweden" },
    { id: "170", text: "Switzerland" },
    { id: "171", text: "Syria" },
    { id: "172", text: "Taiwan" },
    { id: "173", text: "Tajikistan" },
    { id: "174", text: "Tanzania" },
    { id: "175", text: "Thailand" },
    { id: "176", text: "Togo" },
    { id: "177", text: "Tonga" },
    { id: "178", text: "Trinidad and Tobago" },
    { id: "179", text: "Tunisia" },
    { id: "180", text: "Turkey" },
    { id: "181", text: "Turkmenistan" },
    { id: "182", text: "Tuvalu" },
    { id: "183", text: "Uganda" },
    { id: "184", text: "Ukraine" },
    { id: "185", text: "United Arab Emirates" },
    { id: "186", text: "United Kingdom" },
    { id: "187", text: "United States" },
    { id: "188", text: "Uruguay" },
    { id: "189", text: "Uzbekistan" },
    { id: "190", text: "Vanuatu" },
    { id: "191", text: "Vatican City" },
    { id: "192", text: "Venezuela" },
    { id: "193", text: "Vietnam" },
    { id: "194", text: "Yemen" },
    { id: "195", text: "Zambia" },
    { id: "196", text: "Zimbabwe" },
];

export class Product {
    public productId: number;
    public productPrice: number;
    public productQuantity: number;
    public total: number;

    constructor(options: any = {}) {
        this.productId = options.productId;
        this.productPrice = options.productPrice;
        this.productQuantity = options.productQuantity;
        this.total = options.total;
    }
}